@TaskManagmentSystem.API_HostAddress = https://localhost:7296

POST {{TaskManagmentSystem.API_HostAddress}}/register

###

POST {{TaskManagmentSystem.API_HostAddress}}/myTask/
Content-Type: application/json

{
  //CreateMyTaskRequest
}

###

POST {{TaskManagmentSystem.API_HostAddress}}/register

###
